cat:
	cat Makefile

install:
	sudo apt-get install isc-dhcp-server


configure:
	sudo cp ./dhcpd.conf /etc/dhdp
	sudo service isc-dhcp-server restart
 	#sudo service isc-dhcp-server start
 	#sudo service isc-dhcp-server stop 
