#!/usr/bin/env python
# coding: utf-8

# %load_ext autoreload
# %autoreload 2 


# %load watch_now
#!/usr/bin/env python


import os
import xmltodict
from datetime import datetime, timezone, timedelta



from libdvr.titan_classes import get_files_titan_tvpi, get_xml_tvpi, t_schedule_record
from libdvr.titan_classes import init_dvr


logger = init_dvr()

my_fields = {}
my_fields['title'] = 'cbs-test'
my_fields['episode'] = 'One'
my_fields['station'] = 'cbs'
chan = '11'
minor = my_fields['minor'] = '1'
my_fields['duration'] = '00:55'
my_fields['vchan'] = f'v{chan}.{minor}'

now = datetime.now()
future_time = now + timedelta(seconds=10)
current_time = future_time.strftime('%Y%m%d%H%M')
at_time = current_time
print(at_time)
my_fields['at_time'] = at_time


t_schedule_record(my_fields)
    
